steps:
# Build and push candid_api docker
- id: candid-api-docker
  name: gcr.io/cloud-builders/docker
  entrypoint: ./scripts/build-docker.sh
  args: ["candid_api"]
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args: ['-c',
         'gcloud run deploy candidapi
         --image=gcr.io/scenic-cedar-324901/candid_api:latest
         --region=us-west1
         --cpu=1
         --port=8080
         --set-env-vars=DB_PASS=$$DB_PASS,ENV=prod,CLOUD_SQL_CONNECTION_NAME=scenic-cedar-324901:us-west1:candid-postgresql']
  secretEnv: ['DB_PASS']
availableSecrets:
  secretManager:
  - versionName: projects/873434447877/secrets/DB_PASS/versions/1
    env: 'DB_PASS'
images:
- gcr.io/scenic-cedar-324901/candid_api
