"""Add politician relationship to party and body

Revision ID: 1bd58ba1261c
Revises: 7e472d91f21a
Create Date: 2021-12-04 17:22:02.978959

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1bd58ba1261c"
down_revision = "7e472d91f21a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "politicians", sa.Column("political_body_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "politicians", sa.Column("political_party_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "politicians", "political_parties", ["political_party_id"], ["id"]
    )
    op.create_foreign_key(
        None, "politicians", "political_bodies", ["political_body_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "politicians", type_="foreignkey")
    op.drop_constraint(None, "politicians", type_="foreignkey")
    op.drop_column("politicians", "political_party_id")
    op.drop_column("politicians", "political_body_id")
    # ### end Alembic commands ###
