"""Add political party and political body

Revision ID: 7e472d91f21a
Revises: 587cd3f0b770
Create Date: 2021-12-04 16:53:25.416167

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7e472d91f21a"
down_revision = "587cd3f0b770"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "political_bodies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_political_bodies_id"), "political_bodies", ["id"], unique=False
    )
    op.create_table(
        "political_parties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_political_parties_id"), "political_parties", ["id"], unique=False
    )
    op.alter_column(
        "politicians", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.create_index(op.f("ix_politicians_id"), "politicians", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_politicians_id"), table_name="politicians")
    op.alter_column(
        "politicians", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_index(op.f("ix_political_parties_id"), table_name="political_parties")
    op.drop_table("political_parties")
    op.drop_index(op.f("ix_political_bodies_id"), table_name="political_bodies")
    op.drop_table("political_bodies")
    # ### end Alembic commands ###
